name = "ThundaSMP"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0dbbd4f1a818fdb864c52ad4816593d1795a5c4e2cf6d9ea5aa2df9afebf22e3"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"
