name = "ThundaSMP"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bd39e9d86c3c63dbc3af98581e75f4cc61316a8ffe18fc105c2982da313584c7"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"
